# 执行机列表
夜神:
  platformName: Android
  platformVersion: 5.1.1
  deviceName: 127.0.0.1:62001


huaweip20:
  platformName: Android
  platformVersion: 9
  deviceName: CLB0219809003558


# 调用地址
mobile:
  appium01: http://127.0.0.1:4723/wd/hub